### PR TITLE
Implement personalization top tracks + top artists

### PR DESCRIPTION
**Pull request by dropofwill**
Personally I also need the Library, Playlist, and Recommendations 
endpoints, so I wanted to check in before I wrote them all up.

This is the first of the /me endpoints, I've confirmed it works hacking
around in the example app, but don't think there is a good way to test
it with the existing infra, because it requires an access token on
behalf of a user.

Obviously I could hard code an access/refresh token with the correct
scope, but that doesn't scale to the endpoints that make modifications.

Maybe we could use Wiremock to at least verify the TCP/JSON part of the
stack. I also noticed sttp has a test library, but couldn't tell if it
actually uses TCP or just mocks them.

### CODE REVIEW

**Comment by hntd187** [comment]
Yea, I'm not sure how we'd test this and not either make it a useless mock test or expose a user token to the outside token. Either way, this looks good at a glance, you marked this as WIP is it not finished?

**Comment by dropofwill** [comment]
Just in the sense that I hadn't figured out how to do anything beyond a manual test.

I'll rebase and fix that import that codacy is complaining about tomorrow.

**Comment by hntd187** [comment]
I think it's likely more effort to figure out and implement actual tests there than to just verify this empirically and take bug reports instead. The other tests are sufficient to show that the the general infrastructure is good. Sound good?

**Comment by hntd187** [comment]
@dropofwill if you're ready can you rebase and we can merge this?

**Comment by dropofwill** [comment]
Should be good to go, test failure for `"[Gente De Zona]" was not equal to "[Madcon]"`, looks like Pitbull's data changed again.

**Comment by hntd187** [comment]
Curse Mr. Worldwide and his constantly changing data. The price of being the best rapper alive.

**Pull request merged**
